name: bisoflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  appwrite: 
    git: 
      url: https://github.com/MHEien/sdk-for-flutter.git
      ref: main
  cached_network_image: ^3.4.1
  file_picker: ^10.2.2
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  go_router: ^16.1.0
  http: ^1.5.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  equatable: ^2.0.7
  crypto: ^3.0.6
  google_mlkit_text_recognition: ^0.15.0
  syncfusion_flutter_pdf: ^30.2.5
  printing: ^5.13.4
  eventflux: ^2.2.1
  flutter_client_sse:
    git:
      url: https://github.com/pratikbaid3/flutter_client_sse
      path: .
  talker_flutter: ^5.0.0
  talker_dio_logger: ^5.0.0
  flutter_html: ^3.0.0
  permission_handler: ^12.0.1
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  flutter_appauth: ^9.0.1
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0

  


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/images/campus/
   # - assets/icons/
   # - assets/animations/
   # - assets/translations/
  
# fonts:
  # Using system default fonts for better compatibility
