name: bisoflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  appwrite: ^17.1.0
  cached_network_image: ^3.4.1
  file_picker: ^10.2.2
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  go_router: ^16.1.0
  http: ^1.5.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/images/campus/
    - assets/icons/
    - assets/animations/
    - assets/translations/
  
# fonts:
  # Using system default fonts for better compatibility
