// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVvt3C4aCAFKNT2kLW1mYbvM1mgtV1Idg',
    appId: '1:633338868564:android:48eea6bc9a6606bd248ec1',
    messagingSenderId: '633338868564',
    projectId: 'fsbiso',
    databaseURL: 'https://fsbiso-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fsbiso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuPgRmU9btn1Jc7vxIdcIX2WM4ZIQq7sk',
    appId: '1:633338868564:ios:c9fe7577ca37dff1248ec1',
    messagingSenderId: '633338868564',
    projectId: 'fsbiso',
    databaseURL: 'https://fsbiso-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fsbiso.appspot.com',
    iosBundleId: 'com.biso.no',
  );
}
